[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 4321 